version: "3.3"

services:
  postgres_service:
    container_name: dev-postgres
    image: kartoza/postgis:14-3.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_DBNAME=test
    ports:
      - 5432:5432
